### ISSUE TITLE
Automatic sequence and random opcode

### ISSUE THREAD

**Issue by kinwie** [sfz/opcode-suggestions#1]
Most samplers have easier setup for round robin and random regions. While in standard sfz specs, it's defined in more complex way. First, for the cycle round robin, we need to put both `seq_length` and `seq_positon`, while most samplers only need to reset its position value only. Second, for the random, we need to create `lorand` and `hirand` and put a lot of division values, while other samplers can just have one click to enable the random trigger.

So, for more easier sfz instruments creation, a new simpler opcode can be made, like: `seq`=on which the player will cycle through the parsed regions. For random trigger, `rand`=on, then the player will create its own internal random counter for triggering

**Comment by kinwie** [comment]
On a recent found, seq_length can be a handy use for other purposes. I edit the initial comment and just suggest ```seq=N``` opcode

**Comment by kinwie** [comment]
Another behavior refinement may also be good to be implemented.
So, to make the sfz player able to play the round-robin sequence detected from the `seq_position` only, without the requirement of `seq_length`. Highest `seq_position` value will be the `seq_length` value.
And when the `seq_length` is present, it will take over the value set by highest `seq_position`.

**Comment by ghost** [comment]
Hi,
My suggestion is that `seq=on` and `rand=on` could be replaced by `rr_type=` with possible values being `random `, default `round ` (if `seq_position` settings exist - same as current), and default `off` (if `seq_position` settings do not exist). This would remove the risk of putting both  `seq=on` and `rand=on` and the `seq_position` and `seq_length`  would not have to change. That way testing random vs round vs no robins would be as easy as changing one word.

**Comment by kinwie** [comment]
It because `seq`=on and `rand`=on can be used simultaneously in sfz, which can produce a desirable region switching IN A PROPER SFZ PLAYER. So using same opcode twice or more with different values will cause problem imo eg, the present of both `rr_type`=random and `rr_type`=round

Here's a little documentation i made about it
~~<https://github.com/kinwie/sfztest/wiki/sfizz-part-1-seq_-and-_rand>~~
<https://redtide.github.io/sfztest/sfizz-part-1-seq_-and-_rand/>

**Comment by kinwie** [comment]
When using `seq`=on or `rand`=on, we dont need to put `seq_position`, `seq_ length`, or `lorand` `hirand` anymore, which is the main purpose
