### ISSUE TITLE
bg_image= to add a simple background image and gui_xml= to go full Gui change

### ISSUE THREAD

**Issue by ghost** [sfz/opcode-suggestions#16]
When using multiple samplers (Sforzando,  tx16wx), the visual cues are scarce as to what instrument is being used. Aria uses external XML files with a full GUI definition for commercial instruments. Some other samplers also allow the sample instrument author to change the look of the interface. 

Developing a full XML GUI definition might be a way off, but being able to at least change the background image would be a help in adding visual cues to users.

I suggest:
`bg_image=` to point to a simple background image and `gui_xml=` to point to an XML gui definition file.

**Comment by redtide** [comment]
AriaGUI XML is used also for free instruments, but it's not part of the sfz specification, so I'm not sure what a `gui_xml` opcode would be used for.\
There is an [image] opcode described on the Cakewalk Synthesizers book, though I'm not sure if that was intended to be used as splashscreen or background image, but anyway it's up to the player developers if implement it or not, or just use a custom UI preference.

[image]: https://sfzformat.com/opcodes/image

**Comment by ghost** [comment]
"it's not part of the sfz specification" ... I don't think anything on this list is part of the sfz specification. I thought that was the point of this list. If I'm wrong, I'm happy to remove the suggestion.

Anyhow, my thought was to have baby steps, starting with just `bg_image=my_guitar.png`. That would satisfy a bunch of users, since many musicians are put off by XML and just being able to put up a picture of the guitar you just sampled would be satisfying. In the future, the `gui_xml=my_custom_interface.xml` would require more work of course. Aria seems to use the XML to call the sfz files, but that seems backwards to me.

**Comment by redtide** [comment]
The objective of this project, which is indeed not clear, is about to add new opcodes to the specification with a view for a possible v3, though is not a simple task without the participation of most of the current developers (both of samples libraries and sfz players).\
Just my opinion, sfz shouldn't keep UI data information (or at least very minimal like labels), maybe that's also why AriaGUI does the way you noticed.
