### ISSUE TITLE
Multiple Key-Switch Support

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfz/opcode-suggestions#21]
A new header is proposed to allow multiple keyswitch support in SFZ.

`<switch>`

This will allow multiple key-switch groups to be active at the same time. 

For example, 1 group could be assigned to instrument selection: "cymbal" or "drum"
While another group would be assigned mallet type: "hard", "soft", "brush" etc.

Below example would play sine synth if A1 & A3 are active, and only change to saw synth if A1 & B3 are active:

```
<switch> sw_lokey=A1  sw_hikey=A2
<switch> sw_lokey=A3  sw_hikey=A4
<region> sample=*sine sw_last=A1   sw_last=A3
<region> sample=*saw  sw_last=A1   sw_last=B3
```

Use case with two different size cymbals, and different beater types:
```
<switch> sw_lokey=C1  sw_hikey=D1 //16" or 18" cymbal
<switch> sw_lokey=C2  sw_hikey=A2  //type of beater

<region> sample=cymbal_16_sticks.wav        sw_last=C1  sw_last=C2
<region> sample=cymbal_16_hard_mallets.wav  sw_last=C1  sw_last=D2
<region> sample=cymbal_16_soft_mallets.wav  sw_last=C1  sw_last=E2
<region> sample=cymbal_16_rods.wav          sw_last=C1  sw_last=F2
<region> sample=cymbal_16_brushes.wav       sw_last=C1  sw_last=G2
<region> sample=cymbal_16_bow.wav           sw_last=C1  sw_last=A2

<region> sample=cymbal_18_sticks.wav        sw_last=D1  sw_last=C2
<region> sample=cymbal_18_hard_mallets.wav  sw_last=D1  sw_last=D2
<region> sample=cymbal_18_soft_mallets.wav  sw_last=D1  sw_last=E2
<region> sample=cymbal_18_rods.wav          sw_last=D1  sw_last=F2
<region> sample=cymbal_18_brushes.wav       sw_last=D1  sw_last=G2
<region> sample=cymbal_18_bow.wav           sw_last=D1  sw_last=A2
```

Currently- the above example would need to use 12 keyswitches, with the addition of multi-keyswitch support, there would only need to be 8! Which represents a huge reduction in keyswitches for advanced instruments, and allow easier control and creation of keyswitch instruments.

**Comment by DSmolken** [comment]
I think I've used up to 26 keyswitches in an instrument, and this could be a way to cut down on some of that as well. However, that's a different use case - one instrument with a lot of bowed and plucked techniques. This could be used to have some techniques on a single keyswitch (like ordinary sustains), and others with multi (like spiccato and ghost spiccato, or sul tasto sustains and wind noise).

The general problem is I guess that instruments are being sampled with more and more thorough lists of techniques these days, much more so than when the SFZ spec was first created.

**Comment by kinwie** [comment]
I don't think we need a `<switch>` header
Adding these I suppose it will works :
```
sw_lokeyN=
sw_hikeyN=
sw_lastN=
sw_labelN=
sw_defaultN=
```

So, from your example :
```
#define $beater1 sticks
#define $beater2 hard_mallets
#define $beater3 soft_mallets
#define $beater4 rod
#define $beater5 brushes
#define $beater6 bow

<global>
sw_lokey1=C1  sw_hikey1=D1
sw_lokey2=C2  sw_hikey2=A2
sw_default1=C1
sw_default2=C2

<group>
sw_last1=C1
sw_label1=16" cymbal
<region> sample=cymbal_16_sticks.wav        sw_last2=C2 sw_label2=$beater1
<region> sample=cymbal_16_hard_mallets.wav  sw_last2=D2 sw_label2=$beater2
<region> sample=cymbal_16_soft_mallets.wav  sw_last2=E2 sw_label2=$beater3
<region> sample=cymbal_16_rods.wav          sw_last2=F2 sw_label2=$beater4
<region> sample=cymbal_16_brushes.wav       sw_last2=G2 sw_label2=$beater5
<region> sample=cymbal_16_bow.wav           sw_last2=A2 sw_label2=$beater6

<group>
sw_last1=D1
sw_label1=18" cymbal
<region> sample=cymbal_18_sticks.wav        sw_last2=C2 sw_label2=$beater1
<region> sample=cymbal_18_hard_mallets.wav  sw_last2=D2 sw_label2=$beater2
<region> sample=cymbal_18_soft_mallets.wav  sw_last2=E2 sw_label2=$beater3
<region> sample=cymbal_18_rods.wav          sw_last2=F2 sw_label2=$beater4
<region> sample=cymbal_18_brushes.wav       sw_last2=G2 sw_label2=$beater5
<region> sample=cymbal_18_bow.wav           sw_last2=A2 sw_label2=$beater6
```

Then, the player also need to support the multi keyswitches label on the UI

**Comment by AlexMitchellMus** [comment]
Two comments:

* `sw_lokeyN` & `sw_hikeyN` are necessary to define the group's.
* I don't like having to repeat the sw_label in each region. This feels redundant.

**Comment by kinwie** [comment]
The `N` is the group ID

Updated using #define for redundant values
