### ISSUE TITLE
Modulation Source as Delta (change of CC value over time)

### ISSUE THREAD

**Issue by AlexMitchellMus** [sfz/opcode-suggestions#22]
Modulation opcode request: `ondeltaccN` 

Takes a simple first order derivative of a CC's history.

Rising values on the first CC induce positive values in the derivative, and falling values induce negative values in the derivative.

This would allow the user to implement breath vibrato to pitch vibrato conversion.

`ondeltaccN` should also be able to be stacked with `curveccN` etc.

eg: 
```
<region>
sample=*sine
tune_ondeltacc2=100
```
In the above example, when you're increasing breath pressure, you go sharp, and when you're backing off, you go flat. (or use curve 1 if you want the opposite reaction)

Suggested by discord user Mal-2

**Comment by jpcima** [comment]
Possibly, we would want step/smooth/curve equivalents for deltacc.
There is candidate notation `stepdeltaccN/smoothdeltaccN/curvedeltaccN`.
Perhaps `delta` can be shortened to `d`, as used in math notation, but I doubt that it can help readibility.

**Comment by AlexMitchellMus** [comment]
I think given the rest of sfz syntax, keep it to delta.
