### ISSUE TITLE
Well-defined loop crossfading

### ISSUE THREAD

**Issue by sagamusix** [sfz/opcode-suggestions#24]
Currently ([as per this issue](https://github.com/sfzformat/sfzformat.github.io/issues/54)) there are two known implementations of the loop_crossfade opcode, namely in OpenMPT and sfizz. They both use different parameters for the crossfade, and while I'd be more than happy to adjust OpenMPT's curve to match that of sfizz, I think there are actually good reasons for having more than one option. In particular, depending on how well the loop start and end correlate, the fade curve can either reduce or increase the perceived volume of the sample during the fade.  For some samples, a constant volume fade might be good while for others a constant power fade might be better.

I think being able to control the crossfade curve through an additional opcode would be really useful. @jpcima suggested that `<curve>` could be used for that, but I think for that we'd need to support more standard curves, as drawing a crossfade curve with discrete user-provided values is probably way too coarse.

**Comment by sagamusix** [comment]
@jpcima do you also crossfade from the loop end back to the original sample data? OpenMPT does that because it can be important for sustain loops. Should this be an optional feature of crossfades?

**Comment by paulfd** [comment]
There's at least the choices in the crossfades opcodes that are a good starting point ! Probably any addition to loop crossfades should also be valid for all the `xfcurve` opcodes.
