### ISSUE TITLE
Keyboard tracking of envelope generator times (e.g. attack, decay, release) 

### ISSUE THREAD

**Issue by PV70** [sfz/opcode-suggestions#32]
Dear all,

I would propose to add a little feature to SFZ envelope generators which I have always found quite useful in older HW synths (e.g. the Roland JV series): the programmable scaling of envelope times (e.g. attack/decay/release) according to keyboard tracking.

In the most general implementation, a programmer would be allowed to define a separate keyboard tracking value for each envelope time parameter (i.e. attack/decay/release); however, even having a single keyboard tracking parameter affecting the duration of the whole envelope might work to some extent.

The benefit of such keyboard tracking feature would be a very economical modelling of a typical characteristic of resonating acoustic instruments (e.g. pianos/guitars) for which the envelope tends to elapse quicker on higher notes.

Looking at the existing issues in this database, I believe this SFZ opcode proposal may partially answer the requirement expressed in issue #31.

Thank you for your support and keep up the excellent work!

Best regards,
Paolo

**Comment by plgDavid** [comment]
Some ARIA Extension SFZs in the field already have been using a variant of this idea (since 2021 ish)
EG:
offset_mode=percent //switches the offset opcode from its default "offset_mode=samples" behaviour
offset_oncc257=50     //random offset from 0 to half the file

**Comment by PV70** [comment]
Hi David,

Thanks a lot for your answer.

One thing that's not clear to me is whether similar constructs are actually
available for ENV times: can you please elaborate?

Thank you,
Paolo

**Comment by plgDavid** [comment]
I deleted my reply and posted it in the "offset" ticket instead. It was an error on my end. I didnt do anything with env scaling.
