### ISSUE TITLE
Implement `on_locc133` / `on_hicc133` or create `on_key` new opcode

### ISSUE THREAD

**Issue by kinwie** [sfz/opcode-suggestions#5]
These opcodes, `on_locc133` `on_hicc133` or `start_locc133` `start_hicc133`
are listed already but not yet implemented in most sfz players.
CC133 is extended cc for keynumber.
The intention for its use is for triggering release samples that put on a key and triggered from another key.
In practical, it will be used for triggering cymbals release/choke/tail samples.

A short explanation for Drum kit mapping ;

1. Mapped for triggered by e-drum MIDI Controller. In this mapping mode, the function described above can be achieved by the use of `on_locc130` `on_hicc130`. CC130 is polyphonic aftertouch. This is works and commonly supported by most e-drums.
2. Mapped for triggered by Keyboard MIDI Controller or by writing MIDI notes via host's pianoroll. In this mapping mode, the function described above not yet able to be achieved by the use of `on_locc133` `on_hicc133`.

So, either implementing `on_locc133` `on_hicc133` and `start_locc133` `start_hicc133` OR made a new opcode : `on_key` which has the same function

**Comment by kinwie** [comment]
A description and test file for this case has been posted here :
~~https://github.com/kinwie/sfztest/wiki/Cymbal-choke-test-for-edrums-and-keyboard-mapping-mode~~
https://redtide.github.io/sfztest/Cymbal-choke-test-for-edrums-and-keyboard-mapping-mode/

**Comment by redtide** [comment]
or just `on_cc` as generic?
